version: '3'

services:
  web:
    build:
      container_name: web
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - '4000:3000'
    networks:
      - local_network

networks:
  local_network: